### ISSUE TITLE
'selector-no-id' and 'selector-no-universal' are deprecated

### ISSUE THREAD

**Issue by KevinHerklotz** [maximgatilin/stylelint-config#32]
I just saw that my generated config contains deprecated rules. This should be fixed.

> Deprecation Warning: 'selector-no-id' has been deprecated and in 8.0 will be removed. Instead use 'selector-max-id' with '0' as its primary option. See: https://stylelint.io/user-guide/rules/selector-no-id/
> 
> Deprecation Warning: 'selector-no-universal' has been deprecated and in 8.0 will be removed. Instead use 'selector-max-universal' with '0' as its primary option. See: https://stylelint.io/user-guide/rules/selector-no-universal/

**Comment by KimonoVIP** [comment]
Thanks for the cool tool!)
selector-no-universal - This has not been fixed, the error is still there! I could help with pull-request if I understood where it can be corrected.

**Comment by maximgatilin** [comment]
@KimonoVIP URW, sorry now I don't have time to maintain. https://github.com/maximgatilin/stylelint-config/blob/master/src/js/options.js - here you can find options
