### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by maximgatilin** [maximgatilin/stylelint-config#6]

**Comment by maximgatilin** [comment]
Done

**Comment by awebdeveloper** [comment]
is there something for eslint too. If not i am planning to fork yours and create one

**Comment by maximgatilin** [comment]
You are welcome) In this issue i mean adding linting to my project

**Comment by awebdeveloper** [comment]
oh... no problem.  I really liked your this project. 

Do u want to collaborate or  at least give you suggestion now and then
